### ISSUE TITLE
How can make this tabs?

### ISSUE THREAD

**Issue by dmitryvasilevskiy** [pavloniym/nova-options-selector#1]
![image](https://user-images.githubusercontent.com/15924777/204521085-aa690ec1-f4e9-47f8-9890-6b00e335c894.png)

**Comment by Martenvanurk** [comment]
Hey, I'm using this package with those tabs:
https://novapackages.com/packages/eminiarts/nova-tabs

<img width="979" alt="image" src="https://user-images.githubusercontent.com/747146/205329538-bbe9c0e9-6e12-4f22-959e-9d05d22b0f23.png">

**Comment by pavloniym** [comment]
Hello!
Yes, this is https://novapackages.com/packages/eminiarts/nova-tabs + custom css file (for narrow tabs)
